version: "1.0"

services:
  backend-bookmanager:
    platform: linux/amd64
    container_name: backend-bookmanager
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    networks:
      - connect
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data

  web-bookmanager:
    platform: linux/amd64
    container_name: web-bookmanager
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8000:80
volumes:
  postgres:
    name: nest-db
networks:
  connect:
    driver: bridge
