# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.8'
services:
  fe-bookmanager:
    platform: linux/amd64
    container_name: fe-bookmanager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080

#    volumes:
#      - /path/to/nginx-persistence/certs:/certs
#    - ./nginx/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/nginx.conf:ro
#    - ./nginx/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/nginx.conf:ro
